/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/M25zaZvEBZJ
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import React from "react";
import { useAuth } from '../context/AuthContext';
import { AuthenticatedHeader } from './AuthenticatedHeader';

export default function Header() {
  const { isAuthenticated } = useAuth();

  if (isAuthenticated) {
    return <AuthenticatedHeader />;
  }

  return (
    <header className="flex items-center justify-between px-6 py-4 bg-white dark:bg-gray-800">
      <Link href="/">
        <MountainIcon className="h-6 w-6" />
        <span className="sr-only">Primarch Solutions</span>
      </Link>
      <nav className="flex gap-6">
        <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
          Home
        </Link>
        <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
          Features
        </Link>
        <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
          Pricing
        </Link>
        <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
          Contact
        </Link>
      </nav>
      <div className="flex gap-2">
        <Link href="/login">
          <Button variant="outline">Login</Button>
        </Link>
        <Link href="/create">
          <Button >Sign Up</Button>
        </Link>
      </div>
    </header>
  )
}

interface MountainIconProps extends React.SVGProps<SVGSVGElement> {}

function MountainIcon(props: MountainIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
