/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/QoOF6Q5HvfJ
 */
import { Button } from "@/components/ui/button"
import { GroceryAccounts } from "./GroceryAccounts"

export function UserDashboard() {
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
      <div className="w-full max-w-3xl p-8 bg-white rounded-lg shadow-md dark:bg-gray-800">
        <h2 className="text-2xl font-bold text-center text-gray-800 dark:text-gray-100">Linked Grocery Accounts</h2>
        <div className="mt-8 grid gap-4">
          <div className="flex flex-col items-center justify-center p-4 bg-gray-50 rounded-lg shadow-inner dark:bg-gray-700">
            <div className="mt-4 flex flex-wrap justify-center gap-4">
              <GroceryAccounts />
            </div>
          </div>
          <Button className="w-full h-12 bg-blue-800 text-white text-lg rounded-lg shadow-lg transform transition duration-150 ease-in-out hover:scale-105 w-full">Sync</Button>
          <p className="text-sm text-center text-gray-500 dark:text-gray-400">Last updated: 10 minutes ago</p>
        </div>
      </div>
    </div>
  )
}
